### ISSUE TITLE
How does this optimizer work?

### ISSUE THREAD

**Issue by chursaner** [linanqiu/wedding-optimization-simulated-annealing#1]
I found this link from a banana data news email and maybe it’s because I’m accessing github on my phone but I don’t see a readme or example. I am a data scientist getting married in March and would love to play around with something like this!

**Comment by linanqiu** [comment]
Yup it's because you're on mobile. Github doesn't show the jupyter
notebooks well. If you see this on a desktop you'll see all the nice
charts, explanations etc

https://github.com/linanqiu/wedding-optimization-simulated-annealing/blob/master/wedding-optimization.ipynb

**Comment by chursaner** [comment]
Thanks! Readme is great
